<?php

/**
 * @file
 * General functions.
 */

/**
 * Implements hook_theme().
 */
function github_theme($existing, $type, $theme, $path) {
  return [
    'github_formatter' => [
      'variables' => ['avatar' => NULL, 'username' => NULL, 'stargazer' => NULL],
    ],
    'github_issues' => [
      'variables' => ['issues' => NULL],
    ],
    'github_repos' => [
      'variables' => ['repos' => NULL],
    ],
    'github_funding' => [
      'variables' => ['report' => NULL],
    ],
  ];
}
