<?php

/**
 * Load github library.
 */
function github_load_library() {
  $path = libraries_get_path('github-php-client') . '/client/GitHubClient.php';
  require_once($path);
}

/**
 * Implements hook_theme().
 */
function github_theme($existing, $type, $theme, $path) {
  return [
    'github_formatter' => [
      'variables' => ['avatar' => NULL, 'username' => NULL, 'stargazer' => NULL],
    ],
  ];
}
